[package]
name = "nightcrab-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"] }
rustls = "0.23.28"
serde_json = "1.0.140"
webpki-roots = "1.0.1"
